apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'com.bugsnag.android.gradle'

ext {
    versionFile = new File(project.rootDir, 'app/src/main/assets/libopenmw/resources/version')
    calculateVersion = {
        stream = new FileInputStream(versionFile)
        return stream.readLines()[0].trim() + "-" + project.android.defaultConfig.versionCode.toString()
    }
}

android {
    compileSdkVersion 29

    sourceSets {
        main {
            resources {
                srcDir {
                    // To include the wrap.sh script required by ASAN
                    "wrap/res"
                }
            }
        }
    }

    defaultConfig {
        applicationId "com.mrzer0x0.arenamw"
        versionCode 47
        versionName calculateVersion()

        minSdkVersion 21
        targetSdkVersion 28

        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a", "x86", "x86_64"
        }
    }

    lintOptions {
        checkReleaseBuilds false
    }

    compileOptions {
        targetCompatibility 1.8
        sourceCompatibility 1.8
    }

    buildTypes {
        release {
            minifyEnabled false
        }

        debug {
            debuggable false
            //applicationIdSuffix ".debug"
            //debuggable true
        }
    }

    flavorDimensions "version"

    productFlavors {
        mainline {
            dimension "version"
        }

        nightly {
            dimension "version"
            applicationId "com.mrzer0x0.arenamw.nightly"
            versionNameSuffix "-nightly"
        }
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "ArenaMW_${variant.buildType.name}_${defaultConfig.versionName}.apk"
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.0'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'

    implementation project(':storagechooser')

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    implementation 'com.bugsnag:bugsnag-android-ndk:4.+'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.3.3'
    implementation 'androidx.navigation:navigation-ui-ktx:2.3.3'

    testImplementation 'junit:junit:4.12'
}
