if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SOURCE_DIR is required")
endif()
set(_file "${SOURCE_DIR}/src/gl/glsl/glsl_for_es.cpp")
if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "NG-GL4ES shader converter not found: ${_file}")
endif()
file(READ "${_file}" _src)
set(_old_pattern [=[R"(^\s*(?:layout\s*\([^)]*\)\s*)?uniform\s+\w+(?:\s*\[\s*\d+\s*\])?\s+\w+(?:\s*\[\s*\d+\s*\])?\s*;.*$)"]=])
set(_new_pattern [=[R"((^|\n)\s*(?:layout\s*\([^)]*\)\s*)?uniform\s+\w+(?:\s*\[\s*\d+\s*\])?\s+\w+(?:\s*\[\s*\d+\s*\])?\s*;[^\r\n]*)"]=])
string(FIND "${_src}" "std::regex::multiline" _has_multiline)
if(NOT _has_multiline EQUAL -1)
    string(REPLACE "${_old_pattern}" "${_new_pattern}" _src "${_src}")
    string(REPLACE "std::regex::ECMAScript | std::regex::multiline" "std::regex::ECMAScript" _src "${_src}")
    file(WRITE "${_file}" "${_src}")
    message(STATUS "ArenaMW: patched Sisah2/Openmw3 std::regex::multiline for Android NDK r21e")
else()
    string(FIND "${_src}" "${_new_pattern}" _already)
    if(_already EQUAL -1)
        message(WARNING "ArenaMW: NG-GL4ES multiline code changed upstream; compatibility patch was not needed/applied")
    else()
        message(STATUS "ArenaMW: NG-GL4ES Android regex compatibility patch already applied")
    endif()
endif()
